### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by Refuge89** [stoneharry/Edge-of-Chaos#1]
Hi,

Can u upload database for EoC emu?

**Comment by stoneharry** [comment]
Yes, please reply to this Thursday or later to remind me, I am not at home until then.

**Comment by Refuge89** [comment]
Ok, thanks u very much :)

**Comment by Refuge89** [comment]
bump :)

**Comment by stoneharry** [comment]
You can find them here:

https://dl.dropboxusercontent.com/u/1102355/EOC-DBsAndConfig.zip

All account passwords I have reset to 'test' and emails and IP's wiped.

I believe this is the most recent version - it's the most recent version I can find at least.

**Comment by Refuge89** [comment]
Thanks you very much. rly :)
